[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pylint-bug-mre"
description = "MRE of Pylint Import Bug"
version = "0.1.0"
dependencies = [
    "pylint",
]
